### ISSUE TITLE
Changing Popper Arrow Color

### ISSUE THREAD

**Issue by bsl333** [pulsardev/vue-tour#124]
Perhaps I am missing something, but is there an easier way to change the popover arrow color other than overriding the following styles?
```scss
.v-step .v-step__arrow {
    border-color: white !important;       /* set to desired popper arrow color */
    &--dark {
        border-color: white !important;   /* set to desired popper arrow color */
    }
}
.v-step[x-placement^='top'] .v-step__arrow {
    border-left-color: transparent !important;
    border-right-color: transparent !important;
    border-bottom-color: transparent !important;
}

.v-step[x-placement^='bottom'] .v-step__arrow {
    border-left-color: transparent !important;
    border-right-color: transparent !important;
    border-top-color: transparent !important;
}

.v-step[x-placement^='right'] .v-step__arrow {
    border-left-color: transparent !important;
    border-top-color: transparent !important;
    border-bottom-color: transparent !important;
}

.v-step[x-placement^='left'] .v-step__arrow {
    border-top-color: transparent !important;
    border-right-color: transparent !important;
    border-bottom-color: transparent !important;
}
```
