### ISSUE TITLE
Background blur when tooltip open

### ISSUE THREAD

**Issue by tsomorfaruk** [pulsardev/vue-tour#189]
When open a tooltip for touring, then need blur background without tooltip and the highlighted area.

**Comment by VikasAlambaan** [comment]
Is any solution for it

**Comment by saschamander** [comment]
I haven't found a way to make it blurry, but you can add the following CSS-rule to give it a more "highlighted"-look. 
```css
.v-tour__target--highlighted {
    box-shadow: 0 0 0 9999px rgba(0,0,0,.5);
}
```

![grafik](https://user-images.githubusercontent.com/8129465/145543353-d9dbfa2e-e6b3-4650-85ce-e1eae6e07dd9.png)
